from __future__ import annotations

from typing import Protocol

from data_steward.models import (
    Approval,
    AuditEvent,
    Incident,
    LineageEdge,
    Proposal,
    SourceRecord,
)


class Repository(Protocol):
    def initialize(self) -> None: ...
    def reset(self) -> None: ...

    def save_record(self, record: SourceRecord) -> None: ...
    def get_record(self, source: str, record_id: str) -> SourceRecord | None: ...
    def find_records(self, customer_id: str) -> list[SourceRecord]: ...

    def save_incident(self, incident: Incident) -> None: ...
    def get_incident(self, incident_id: str) -> Incident | None: ...
    def list_incidents(self) -> list[Incident]: ...

    def save_proposal(self, proposal: Proposal) -> None: ...
    def get_proposal(self, proposal_id: str) -> Proposal | None: ...
    def list_proposals(self, incident_id: str | None = None) -> list[Proposal]: ...

    def save_approval(self, approval: Approval) -> None: ...
    def get_approval(self, proposal_id: str) -> Approval | None: ...
    def list_approvals(self) -> list[Approval]: ...

    def save_lineage(self, edge: LineageEdge) -> None: ...
    def get_lineage(self, target_record_id: str) -> list[LineageEdge]: ...

    def append_audit(self, event: AuditEvent) -> None: ...
    def get_audit(self, incident_id: str | None = None) -> list[AuditEvent]: ...
